# Generated by Django 5.1 on 2024-09-08 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="blog",
            name="slug",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Путь"
            ),
        ),
    ]
