# Generated by Django 5.1 on 2024-08-25 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_product_manufactured_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Введите имя", max_length=100, verbose_name="Имя"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        help_text="Введите телефон для связи",
                        max_length=20,
                        verbose_name="Телефон для связи",
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        help_text="Введите текст сообщения",
                        verbose_name="Текст сообщения",
                    ),
                ),
            ],
            options={
                "verbose_name": "Контакт",
                "verbose_name_plural": "Контакты",
                "ordering": ("name",),
            },
        ),
        migrations.RemoveField(
            model_name="product",
            name="manufactured_at",
        ),
    ]
