# Generated by Django 5.1 on 2024-08-27 17:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_contact_remove_product_manufactured_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                help_text="Введите дату создания",
                verbose_name="Дата создания",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="product",
            name="created_up",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Введите дату изменения",
                verbose_name="Дата изменения",
            ),
        ),
    ]
