# Generated by Django 5.1 on 2024-08-27 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_alter_product_created_at_alter_product_created_up"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="created_up",
            new_name="updated_at",
        ),
    ]
