# Generated by Django 5.0.6 on 2024-09-18 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_rename_created_up_product_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_version', models.CharField(help_text='Введите номер версии', max_length=10, verbose_name='Номер версии')),
                ('name', models.CharField(blank=True, help_text='Введите наименование версии', max_length=100, null=True, verbose_name='Наименование версии')),
                ('is_version', models.BooleanField(default=True, verbose_name='Признак текущей версии')),
                ('product', models.ForeignKey(blank=True, help_text='Введите продукт', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions', to='catalog.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Версия',
                'verbose_name_plural': 'Версии',
                'ordering': ('number_version',),
            },
        ),
    ]
