# Generated by Django 5.0.6 on 2024-10-04 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_product_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('product_name',), 'permissions': [('can_edit_published', 'Can edit published'), ('can_edit_product_description', 'Can edit description'), ('can_edit_category_product', 'Can edit category')], 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AddField(
            model_name='product',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Отметить для публикации', verbose_name='Опубликовано'),
        ),
    ]
